version: '2'

services:
  solr:
    image: datacite/solr
    ports:
      - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/home
  db:
    environment:
      MYSQL_DATABASE: datacite
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
    ports:
      - "3307:3306"
volumes:
  data:
